### ISSUE TITLE
Fix tab/typo in section Defining and importing the host function

### ISSUE THREAD

**Issue by dmeijboom** [wasmerio/docs.wasmer.io#128]
It seems that `endtag` instead of `endtab` in the Defining and importing the host function section (Ruby) breaks the tabs. Currently the "Ruby" tab is empty while there is a tab called "Untitled" with the content of the "Ruby" tab.

Fix: https://github.com/wasmerio/docs.wasmer.io/pull/127

**Comment by Hywan** [comment]
Closed by #127.
