### ISSUE TITLE
Error in "How to use packages" on https://wasmer.io/

### ISSUE THREAD

**Issue by dazzag24** [wasmerio/docs.wasmer.io#15]
Following the how to use packages guide:

<img width="790" alt="image" src="https://github.com/wasmerio/docs.wasmer.io/assets/1055831/ffc66e8f-112e-45cc-9a93-aededd48c9b9">

it states:

```
wasmer run syrusakbary/cowsay hello wasmer
```

But this does not provide the documented output

```
❯ wasmer run syrusakbary/cowsay hello wasmer
error: The `cowsay@0.2.0` package doesn't have a default entrypoint, but has multiple available commands:
│   1: You can run any of those by using the --command-name=COMMAND flag
│   2: `cowsay`, `cowthink`
╰─▶ 3:   -> wasmer run cowsay@0.2.0 --command-name=cowsay
```

The docs need updating to this:
```
❯ wasmer run syrusakbary/cowsay --command-name=cowsay hello wasmer
 ______________
< hello wasmer >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
               ||----w |
                ||     ||
```

**Comment by dynamite-bud** [comment]
In the new docs that live [here](https://docs.wasmer.io/runtime/cli). The command is already updated to:
`wasmer run syrusakbary/cowsay --command=cowthink Hello world`.

I think you mistakenly referred to the old docs.

**Comment by dazzag24** [comment]
These are the docs currently live at https://wasmer.io/

Click on "How to use packages" in green box.

<img width="1185" alt="image" src="https://github.com/wasmerio/docs.wasmer.io/assets/1055831/93c60248-e894-4997-a4c5-36c5d11e141e">
