### ISSUE TITLE
Mac specific details missing from wasmer-js documentation

### ISSUE THREAD

**Issue by ChrisWhealy** [wasmerio/docs.wasmer.io#19]
The wasmer-js documentation needs some Mac-specific details added to it

Parcel depends on node-gyp which (on a Mac at least) depends on the Xcode command line tools, which in turn, depend on Xcode being installed

Happy to add these details myself...

**Comment by torch2424** [comment]
@ChrisWhealy Ah good point! Thanks for mentioning this! 😄 

> Happy to add these details myself...

Yes! Feel free to open a PR. Our team would be happy to review and merge it  👍

**Comment by ChrisWhealy** [comment]
See https://github.com/wasmerio/docs.wasmer.io/pull/23

**Comment by syrusakbary** [comment]
Closing issue as #23 just got merged :)
