### ISSUE TITLE
Investigate if wasm module examples are practical / Make the clock_time_get example Wasm Module return the the time.

### ISSUE THREAD

**Issue by torch2424** [wasmerio/docs.wasmer.io#24]
Currently, this just prints out the string "Done!". Which was perfect for when we were testing / building the wasm-trasnformer, but now it does not make much sense for the docs 😄 

relates to https://github.com/wasmerio/docs.wasmer.io/issues/20#issuecomment-575625369

**Comment by ChrisWhealy** [comment]
Hi Aaron

Sorry to be picky, but I've noticed a more few discrepancies.  It would be great if these could also be addressed:

* As it stands, the demo code doesn't pass anything from JavaScript to WebAssembly.  In order actually to demo what we're talking about, shouldn't we pass a JavaScript `BigInt` into a native function and get a 64-bit response back?
* Shouldn't the `clock_time_get` WebAssembly module use the same native function type definition described in the [docs](https://github.com/WebAssembly/WASI/blob/master/phases/snapshot/docs.md#-clock_time_getid-clockid-precision-timestamp---errno-timestamp)?  
    This would be:
    `(type $t0 (func (param u32 u64) (result u64)))`
    Not the existing
    `(type $t0 (func (param i32 i64 i32) (result i32)))`

🤔

**Comment by torch2424** [comment]
@ChrisWhealy

> Sorry to be picky, but I've noticed a more few discrepancies. It would be great if these could also be addressed:

No worries about being picky, we need that and learn a lot from it! 😄 👍 

> s it stands, the demo code doesn't pass anything from JavaScript to WebAssembly. In order actually to demo what we're talking about, shouldn't we pass a JavaScript BigInt into a native function and get a 64-bit response back?

Ah, so it does do calling, the user doesn't have to explicitly pass something to the wasm module to handle this. The passing occurs because the `@wasmer/wasi` polyfill is imported into the wasm module. The wasm module then called the JS import, which needs to be trampolined. So perhaps this issue is probably just that we need a better explanation on this as well as the "Done!" fix 😄 

> Shouldn't the clock_time_get WebAssembly module use the same native function type definition described in the docs?

Hmm are you sure you sure you got the correct function signature from the wat output? 🤔 I compiled the module with wasienv, unless it was already pre-lowered (incorrectly), it should be the the `(type $t0 (func (param i32 i64) (result i64)))` function signature? 🤔

**Comment by ChrisWhealy** [comment]
> Hmm are you sure you sure you got the correct function signature from the wat output? 🤔 I compiled the module with wasienv, unless it was already pre-lowered (incorrectly), it should be the the (type $t0 (func (param i32 i64) (result i64))) function signature? 🤔

Hmmm, when I compile the WASM module, the type declaration I need to use is 

`(type $t0 (func (param i32 i64 i32) (result i32)))`

That said, I'm getting an i32 left on the stack after the call, but 8 bytes of time data are written to the memory offset specified in the third parameter

**Comment by torch2424** [comment]
@ChrisWhealy Hmmm, thanks for explaining that! I'll take a closer look. If anything, we can use a more straightforward WASI binding with an `i64` to make it more apparent 😄

**Comment by ChrisWhealy** [comment]
Also, take a look at https://github.com/ChrisWhealy/clock_time_get to see a working example

**Comment by torch2424** [comment]
@ChrisWhealy Just started reading your email, and taking a look at this now 😄 👍

**Comment by torch2424** [comment]
So After looking at the other example modules we are using for the rust and C integration, the only example that has a "weird" module is the wasmer-js example with the clock_time_get. The rest have clear names on what the module does, and show off a clear use case in terms of their functionality.

Considering our `clock_time-get` module, I realized that it wasn't written in C, and instead was [hand-written and compiled with wasm2wat](https://github.com/wasmerio/wasmer-js/blob/master/crates/wasm_transformer/wasm_module_examples/clock_time_get.wat) since it made more sense for our testing of wasm-transformer at the time.

Therefore, I'm going to go ahead and write this module in AssemblyScript (since JS users will probably have the easiest time reading AssemblyScript), and make it have a more practical output 😄 👍

**Comment by ChrisWhealy** [comment]
@torch24242
Please also consider my version of [`clock_time_get`](https://github.com/ChrisWhealy/clock_time_get/blob/master/wasm_lib/clock_time_get.wat).

Yes, this was also hand-written in WebAssembly Text and compiled using `wat2wasm`, but I trust that with the extra explanatory comments I've added into the coding, the functionality is self-explanatory...

**Comment by syrusakbary** [comment]
Our docs now use raw wat files for the examples.
Closing the issue
