### ISSUE TITLE
Invalid resource path : /edge - Getting started Guide

### ISSUE THREAD

**Issue by iamshreeram** [wasmerio/docs.wasmer.io#25]
The path doesn't exist - https://docs.wasmer.io/get-started

Issue Location : https://github.com/wasmerio/docs.wasmer.io/blob/main/pages/edge/index.mdx#L115

Fix : I think it must be - https://docs.wasmer.io/edge/get-started

**Comment by iamshreeram** [comment]
PR - #26

**Comment by iamshreeram** [comment]
@ptitSeb , The issue exist even after merging #26

**Comment by dynamite-bud** [comment]
Fixed in #30
