### ISSUE TITLE
404 when navigating to project source code

### ISSUE THREAD

**Issue by KaiserKarel** [wasmerio/docs.wasmer.io#37]
When checking out examples, the link to the GitHub source repo 404s

https://docs.wasmer.io/runtime/rust-integration/docs/runtime-rust-integration-examples-passing-data
https://github.com/wasmerio/docs.wasmer.io/tree/master/docs/runtime/rust-integration/examples/passing_data.rs

GitHub allows linking to specific commits instead of branches. This takes more work when updating the docs, but if related repositories are renamed or files moved, links still remain valid, since static documentation is linked against a fixed set of commits.

**Comment by syrusakbary** [comment]
Thanks for opening the issue!
You are completely right.

Right now we are transitioning the docs to a new version (you can check it here temporarily https://new-docs.wasmer.io), so that’s why the examples are broken I’m the old version.

We will make the new docs version the official very soon! :)

**Comment by syrusakbary** [comment]
Ups, wrong issue linked

**Comment by jubianchi** [comment]
I think this issue is not relevant anymore as examples.

Also, with #76 this will be fixed.

Closing.
