### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by bsahbi** [wasmerio/docs.wasmer.io#38]
https://docs.wasmer.io/ecosystem/wapm/cli
https://docs.wasmer.io/ecosystem/wapm/getting-started

**Comment by iamshreeram** [comment]
@bsahbi - https://docs.wasmer.io/ecosystem/wapm/getting-started is redirected to [WAPM - Getting started](https://docs.wasmer.io/registry/get-started). you can use the new hyper link. 

Could you please share the reference to above links in the wasmer document? thanks!

**Comment by bsahbi** [comment]
@dynamite-bud  can you follow up this comment please

**Comment by dynamite-bud** [comment]
This has been fixed @iamshreeram
