### ISSUE TITLE
Get error when compiling passing-data.c example

### ISSUE THREAD

**Issue by tuandt** [wasmerio/docs.wasmer.io#43]
Hi,
I got this error when compiling passing-data.c example:

`
passing-data.c: In function ‘get_length_of_memory’:
passing-data.c:132:36: warning: passing argument 1 of ‘wasmer_memory_data_length’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  132 |   return wasmer_memory_data_length(memory);
      |                                    ^~~~~~
In file included from passing-data.c:2:
/home/osboxes/wasmer-c-api/include/wasmer.h:1174:53: note: expected ‘wasmer_memory_t *’ {aka ‘struct <anonymous> *’} but argument is of type ‘const wasmer_memory_t *’ {aka ‘const struct <anonymous> *’}
 1174 | uint32_t wasmer_memory_data_length(wasmer_memory_t *memory);
`

Could anyone please help? I am using this api: 
https://github.com/wasmerio/wasmer/releases/download/0.16.2/wasmer-c-api-linux-amd64.tar.gz

Thanks.

**Comment by MarkMcCaskey** [comment]
Thanks for the bug report!

This looks like an issue with the wasmer c API.  I tested this locally and it was a warning, not an error (on OSX with clang).  Allowing that warning in the mean-time will help, I'll file an issue on wasmerio/wasmer about this!
