### ISSUE TITLE
loading Wasm from registry behaves differently (doesn't work) than loading from local file

### ISSUE THREAD

**Issue by kandros** [wasmerio/docs.wasmer.io#81]
Following the tutorial for _markdown-editor-improved_  I've noticed that using the version published on the registry 

```
import { init, Wasmer, Command } from "@wasmer/sdk";

async function initialize() {
  await init();
  return await Wasmer.fromRegistry("wasmer-examples/markdown-renderer");
}
```

either `wasmer-examples/markdown-renderer` or the one I've published `@kandros/markdown-renderer` the markdown transformation doesn't work (video below)

https://github.com/wasmerio/docs.wasmer.io/assets/4562878/c01bed27-045b-4f80-8707-de57071926fe

While using the locally imported version it does work!

⚠️⚠️ NB: when running the package using `wasmer` CLI it's working as intended!

https://github.com/wasmerio/docs.wasmer.io/assets/4562878/0d514b1a-f37e-4208-9dc3-408fe526a6bf

**Comment by shawvyu** [comment]
me too
