### ISSUE TITLE
Explore/Search functionality seems broken on the website.

### ISSUE THREAD

**Issue by johnmw** [wasmerio/docs.wasmer.io#91]
As a new user I'm having a lot of trouble exploring packages on the website. 

Firstly, on the docs registry page (https://docs.wasmer.io/registry) the "search for packages" link 404s.

Then (and sorry if this is not the right project - please let me know where to go) on the https://wasmer.io/explore page, it is very hard to explore new packages:

- The category tab buttons (Quick sites, Widgets, Databases etc) have a "prohibited" icon that pops up on hover and don't seem to work (before and after searching). 
- The search dropdown in the top right finds results but doesn't do anything when I try to click on a result.

**Comment by ayys** [comment]
> The category tab buttons (Quick sites, Widgets, Databases etc) have a "prohibited" icon that pops up on hover and don't seem to work (before and after searching).

The rationale behind this is to let the users know that there aren't any packages in the specific tabs that match the search filters. Ofc I can see how that is confusing to users.

I think it makes sense to just hide the empty tabs, or even let the tabs be empty with a message "There are no packages in this category that match your search filters. `<button>Clear search filters</button>`"

> The search dropdown in the top right finds results but doesn't do anything when I try to click on a result.

Thanks for reporting this. There is already an internal ticket for it on the wasmer.io website's repo (private), but it's good to know that users are facing this issue as well. I'll ask to bump up the priority on the ticket. Thank you for reporting this <3

**Comment by ayys** [comment]
@johnmw I am going to close this issue since all the work needed on docs.wasmer.io is done. 

note: I had to hard-refresh docs.wasmer.io to see the changes, so you may need to do that as well.
